---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: bookssvc-rs
  labels:
   app: bookssvc
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: bookssvc
  template:
    metadata: 
      name: bookssvc
      labels:
        app: bookssvc
    spec:
      containers:
        - name: books-svc
          image: shaikkhajaibrahim/libbookssvc:1.0
          env:
            - name: DATABASE_URL
              value: "postgresql://user:password@booksdb-svc:5432/booksdb"
            - name: SECRET_KEY
              value: "YtDEVWnL35aAIP-5yxeLjAZ49R920-mMNDfwPyWULu63HFsYzo0f-LO2InxC8eu428k"
          ports:
           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata: 
  name: books-svc
spec: 
  type: NodePort
  ports: 
    - port: 8000
      targetPort: 8000
  selector: 
    app: bookssvc