---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: library-webstore
  labels:
    app: library
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
        - name: lib-container
          image: shaikkhajaibrahim/libwebstore:1.0
          env:
            - name: REACT_APP_BACKEND_API_URL
              value: http://:8000/api/v1
            - name: REACT_APP_BOOKS_API_URL
              value: http://:8000/api/v1/books
            - name: REACT_APP_USERS_API_URL
              value: http://:8000/api/v1/users
          ports: 
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata: 
  name: library-svc
spec: 
  type: LoadBalancer
  ports: 
    - port: 80
      targetPort: 3000
  selector: 
    app: library
