---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: userdb-rs
  labels:
    app: users
spec:
  minReadySeconds: 5
  replicas: 1
  selector: 
    matchLabels:
      app: users
  template: 
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: userdb
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: usersdb
          ports:
            - containerPort: 5432
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata: 
  name: userdb-svc
spec: 
  type: ClusterIP
  ports: 
    - port: 5432
      targetPort: 5432
  selector: 
    app: users
