---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-frontend
  labels:
    app: library
spec:
  minReadySeconds: 5
  
  replicas: 3
  selector:
    matchLabels:
      app: library
  strategy:
    type: Recreate
  template:
    metadata:
      name: lib-fe
      labels:
        app: library
    spec:
      containers:
        - name: library-frontend
          image: shaikkhajaibrahim/libwebstore:1.0
          envFrom:
            - configMapRef:
                name: library-frontend-configmap
          ports: 
            - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata: 
  name: library-svc
spec:
  type: NodePort
  selector:
    app: library
  ports:
    - port: 80
      targetPort: 3000
  

