---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-svc
spec:
  minReadySeconds: 5
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: bookssvc
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels: 
        app: bookssvc
    spec:
      containers:
        - name: books-svc
          image: shaikkhajaibrahim/libbookssvc:1.0
          envFrom:
            - configMapRef:
                name: books-svc-config
          resources:
            requests: 
              memory: "50Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata: 
  name: books-svc
spec: 
  type: NodePort
  ports: 
    - port: 8000
      targetPort: 8000
  selector: 
    app: bookssvc