---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: books-db
spec:
  minReadySeconds: 0
  replicas: 1
  revisionHistoryLimit: 5
  selector: 
    matchLabels:
      app: booksdb
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template: 
    metadata:
      labels:
        app: booksdb
    spec:
      containers:
        - name: books-db
          image: postgres:15-alpine
          envFrom: 
            - secretRef:
                name: books-db-secrets
                optional: True
          resources:
            requests: 
              memory: "50Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          
          ports:
            - containerPort: 5432
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata: 
  name: booksdb-svc
spec: 
  type: ClusterIP
  ports: 
    - port: 5432
      targetPort: 5432
  selector: 
    app: booksdb
      
